#!/bin/bash
set -e

# vm-setup: One-command server bootstrap
# Usage: curl -fsSL https://raw.githubusercontent.com/pranavb-senslyze/vm-setup/main/install.sh | bash

REPO_URL="https://raw.githubusercontent.com/pranavb-senslyze/vm-setup/main"
MISE_DIR="$HOME/.local/bin"
CONFIG_DIR="$HOME/.config/mise"
BASHRC="$HOME/.bashrc"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if a line exists in bashrc
line_exists_in_bashrc() {
    grep -Fxq "$1" "$BASHRC" 2>/dev/null
}

# Add line to bashrc if it doesn't exist
add_to_bashrc() {
    local line="$1"
    if ! line_exists_in_bashrc "$line"; then
        echo "$line" >> "$BASHRC"
        log_info "Added to ~/.bashrc: $line"
    else
        log_warn "Already in ~/.bashrc: $line"
    fi
}

# Download config.json from repo
download_config() {
    log_info "Downloading config.json from repo..."
    CONFIG_JSON=$(curl -fsSL "$REPO_URL/config.json")
    if [ -z "$CONFIG_JSON" ]; then
        log_error "Failed to download config.json"
        exit 1
    fi
    log_info "Config downloaded successfully"
}

# Parse JSON and generate mise config
generate_mise_config() {
    log_info "Generating mise configuration..."
    
    # Check for jq or python for JSON parsing
    if command -v jq &> /dev/null; then
        TOOLS=$(echo "$CONFIG_JSON" | jq -r '.tools | keys[]')
        GLOBAL_BASHRC=$(echo "$CONFIG_JSON" | jq -r '.global_bashrc[]')
    elif command -v python3 &> /dev/null; then
        TOOLS=$(echo "$CONFIG_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print('\n'.join(d['tools'].keys()))")
        GLOBAL_BASHRC=$(echo "$CONFIG_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print('\n'.join(d.get('global_bashrc', []))")
    else
        log_error "Neither jq nor python3 found. Please install one of them first."
        exit 1
    fi
    
    # Create mise config directory
    mkdir -p "$CONFIG_DIR"
    
    # Generate mise.toml content
    {
        echo "# Auto-generated by vm-setup"
        echo "# Last updated: $(date -Iseconds)"
        echo ""
        echo "[tools]"
        
        # Add each tool
        for tool in $TOOLS; do
            if command -v jq &> /dev/null; then
                version=$(echo "$CONFIG_JSON" | jq -r ".tools.\"$tool\".version // \"latest\"")
            else
                version=$(echo "$CONFIG_JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['tools'].get('$tool', {}).get('version', 'latest'))")
            fi
            echo "$tool = \"$version\""
        done
        
        echo ""
        echo "[settings]"
        echo "not_found_auto_install = true"
        echo "jobs = 4"
    } > "$CONFIG_DIR/config.toml"
    
    log_info "Generated ~/.config/mise/config.toml"
}

# Update bashrc with global and tool-specific lines
update_bashrc() {
    log_info "Updating ~/.bashrc..."
    
    # Add global bashrc lines
    echo "$GLOBAL_BASHRC" | while IFS= read -r line; do
        if [ -n "$line" ]; then
            add_to_bashrc "$line"
        fi
    done
    
    # Add tool-specific bashrc lines
    for tool in $TOOLS; do
        if command -v jq &> /dev/null; then
            bashrc_lines=$(echo "$CONFIG_JSON" | jq -r ".tools.\"$tool\".bashrc // [] | .[]")
        else
            bashrc_lines=$(echo "$CONFIG_JSON" | python3 -c "
import json,sys
d=json.load(sys.stdin)
lines=d['tools'].get('$tool', {}).get('bashrc', [])
for line in lines:
    print(line)
")
        fi
        
        if [ -n "$bashrc_lines" ]; then
            echo "$bashrc_lines" | while IFS= read -r line; do
                if [ -n "$line" ]; then
                    add_to_bashrc "$line"
                fi
            done
        fi
    done
}

# Install mise
install_mise() {
    if command -v mise &> /dev/null; then
        log_warn "mise is already installed"
        return
    fi
    
    log_info "Installing mise..."
    curl https://mise.run | sh
    
    # Add mise to current session PATH
    export PATH="$MISE_DIR:$PATH"
    
    log_info "mise installed successfully"
}

# Install all tools
install_tools() {
    log_info "Installing tools with mise..."
    mise install
    log_info "All tools installed successfully"
}

# Main execution
main() {
    log_info "Starting vm-setup..."
    log_info "This will install mise and configure your server"
    echo ""
    
    # Step 1: Install mise
    install_mise
    
    # Step 2: Download config
    download_config
    
    # Step 3: Generate mise config
    generate_mise_config
    
    # Step 4: Install tools
    install_tools
    
    # Step 5: Update bashrc
    update_bashrc
    
    echo ""
    log_info "Setup complete!"
    echo ""
    log_info "Tools installed: $(echo $TOOLS | tr '\n' ' ')"
    echo ""
    
    # Source bashrc to make tools available immediately (within this script session)
    if [ -f "$BASHRC" ]; then
        log_info "Activating tools in current session..."
        source "$BASHRC"
        log_info "Tools are now available in this session!"
    fi
    
    echo ""
    log_info "Tip: Start a new shell or run 'exec bash' for tools in new sessions"
}

main "$@"
